### ISSUE TITLE
Pacemaker blocks notefield when Center1Player is used

### ISSUE THREAD

**Issue by kyzentun** [dguzek/Simply-Love-SM5#46] opened 2016-06-18 03:36 UTC
http://i.imgur.com/ylYpLCo.png

lol, I don't even know how you managed to make hold bodies go over the pacemaker while taps go under it.  This is hilariscrewy.

I tried sticking stuff in the underlay in my theme, and this stuff didn't happen.  So it must be something strange you're doing to the underlay.

**Comment by dguzek** [comment] 2016-06-18 19:55
That's a pretty good bug!  :)

**Comment by kyzentun** [comment] 2016-06-18 20:04
Nope, that was in current git master, not 5.1.

5.1 has a different draw ordering system anyway, so holds are always under taps.

**Comment by dguzek** [comment] 2016-06-21 07:42
I think this issue is resolved as of fc86bebf58d292274d03f367e9406633f1dc5ea3.  

I've been unable to reproduce the part of the bug in which hold bodies went over the Pacemaker, while taps went under it.  If you're able to reliably reproduce it and send instructions on how I can do so, @kyzentun, I can look into it.

For now, I am closing this issue.

**Closed by dguzek** 2016-06-21 07:42 UTC

**Comment by kyzentun** [comment] 2016-06-21 14:54
Taps going behind the pacemaker only happens with 3D noteskins.  It happens because your Border function uses the z buffer for masking out a quad.  When masking is not used, notes stay on top just fine:
http://i.imgur.com/yIBiwWc.png

Your quad for clearing the z buffer doesn't work because it is fully transparent.  If the diffusealpha of an actor is 0, it is not drawn, and the z buffer clearing only happens when it's actually drawn.

I'm changing the notefield to clear the z buffer itself before it draws the notes to deal with this problem.

Side note:  Somebody who uses Center1Player and this theme probably won't like having no pacemaker.  Not a good solution.  If you're hiding it to avoid having a distraction behind the notes, it'll still be a problem on double.  I always scoffed at the ITG3 theme that had F/E/G counts, but disabled them in double.

**Comment by dguzek** [comment] 2016-06-21 15:01
> Somebody who uses Center1Player and this theme probably won't like having no pacemaker. 

What do you mean by this? My solution when Center1Player is true is to collapse the Pacemaker graphs to the smaller sized previously reserved for versus play, and place them to the right of the playfield.  Is there something I missed?

**Comment by kyzentun** [comment] 2016-06-21 15:02
Oh, when I was glancing through your commit I just saw it setting visible to false in Center1Player mode.

**Comment by dguzek** [comment] 2016-06-21 15:04
No problem; thanks for finding the bug in the first place.
