### ISSUE TITLE
GS High Score is shown instead of Local High Score even if the latter is higher

### ISSUE THREAD

**Issue by Roujo** [dguzek/Simply-Love-SM5#317] opened 2021-05-24 00:35 UTC
In the following (hypothetical :eyes:) situation:
- You have played a chart in a tournament pack, say "U Got 2 Know" in ECFA 2019 Upper, and got around 88.02. You didn't submit that score to GS, since you didn't think it'd be ranked.
- You play the chart using the GS Launcher, get 82.85. As it turns out, that chart is ranked in "The Legend of Zim 5", so the score submits and you get the "GS Personal Best" text at the top of the result screen, which makes sense since that's the highest score GS knows about.
- **Back on the song wheel, your high score is now 82.85, even though you have a higher (unsubmitted) score.** That higher score is even reflected in that the displayed letter grade is A+, which correct for 88.02.

Is this the intended behaviour? I see two problems with this
- The displayed letter grade should match the displayed high score, and;
- I'd rather see my actual PB on the chart, so the highest score between GS and Local.

I'd be okay with the letter grade suddenly changing to a higher one once the theme realizes that my GS high score is higher than what it knew about locally.

Hypothetical screenshots attached ;)

82.85 high score, A+ on song wheel:
![image](https://user-images.githubusercontent.com/706916/119282150-87da7a00-bc06-11eb-86b8-d155ae7ac2de.png)

Actual local HS is 88.02:
![image](https://user-images.githubusercontent.com/706916/119282190-b0627400-bc06-11eb-816e-6c3de7b8d60d.png)

**Comment by teejusb** [comment] 2021-05-24 01:01
Yes this is intended behavior for now. In the release notes we already note that the song wheel rankings may not align with the GrooveStats scores. We don't do any reconciliation because the scores all local scores are extracted from stats.xml and doing any manual manipulation is not a good idea.

We recognize this issue and it is on our radar. In the future we plan on building a hash cache similar to Waterfall which will address these issue as we can reconcile scores then, but that is not the case for the moment.

**Comment by Roujo** [comment] 2021-05-24 01:04
I understand that writing scores to Stats.xml is a Big Endeavour™ that shouldn't be taken lightly, yeah. ^^

In this case, though, the local score is on the very same song - it's the score that's shown if I launch SL 5.0 without the launcher.

In the meantime, would it be possible to just show `max(GSScore, LocalScore)` there without touching Stats.xml? That way I'd at least see my PB on the song selection screen. As it is, it's a bit of a pain to see if it's a score I can improve or not - I see 72, go for the score, get a 85... but turns out my actual PB is 95. It's a bit demoralizing. =P

**Comment by teejusb** [comment] 2021-05-24 17:18
Fixed in https://github.com/Simply-Love/Simply-Love-SM5/pull/318 Thanks for the PR!

**Closed as completed by teejusb** 2021-05-24 17:18 UTC
Labels: enhancement
