### ISSUE TITLE
Couples and routine mode

### ISSUE THREAD

**Issue by skyli91** [dguzek/Simply-Love-SM5#47] opened 2016-06-23 17:15 UTC
I hope these modes will come to the theme too as stepmania default theme has it :)

**Comment by dguzek** [comment] 2016-06-28 00:54
What is the status of Couples mode for Gameplay?  Does it work without bugs/issues?  I've never tried it.

I know that Routine Mode's gamepaly and scoring are too badly broken for me to comfortably add it into the theme.  (I've looked into already!)

**Comment by dguzek** [comment] 2016-07-27 13:36
Routine mode may be selectable in the default theme, but gameplay for it is still quite broken.

Couples mode I am unsure of (I asked @skyli91 whether it worked one month ago, and have not received a response).

At this time, I'm going to close this issue.  If you find that couples gameplay, evaluation, and evaluation summary work as intended, @skyli91, let me know, and we can reopen this issue at that time.

**Closed by dguzek** 2016-07-27 13:36 UTC

**Comment by DXUltimate** [comment] 2016-08-31 11:26
Ooh, routine mode, I want to chime in about this actually.

From what I recall, routine mode does actually work on current versions of StepMania, although I have only seen it work in the PUMP gamemode since. I've never had any problems with it at all as I have been making a ton of pump-routine files with the default theme. I can see why you say it is broken though, since it register as a "two player" mode and not a "one player" mode, kinda like how Infinity works. I will show you;

This is 4 panel routine I made up just to test for you.
https://youtu.be/OWO4-ApvxKM

Now, this actually works for 4p and 5p so far, so I would assume that any other gamemode that is supported should work with it as well, provided the required noteskins are in place for it it work.

*inserts slight hint for support for more 2 players in routine mode* =P

I know not many people use 4 panel routine mode right now since it is not supported on ITG machines that aren't using the SM5 engine, but if it were, I'm sure this mode would be a lot more popular.

**Comment by dguzek** [comment] 2016-08-31 13:48
The video you linked to shows RoutineMode working with Autoplay turned on.  Can you verify that RoutineMode works when buttons are actually being pressed by players?

The last time I tried it (three years ago), *that* was when it broke (all input was directed to PLAYER_1, causing PLAYER_2 to fail) and I'm fairly confident that no code has been added to the engine to fix it, since.

**Comment by DXUltimate** [comment] 2016-08-31 17:13
Definitely, I will try this out when I get home tonight.

**Comment by DXUltimate** [comment] 2016-09-03 20:49
Alright sorry that took forever to do. I got heavily sidetracked on
multiple things. Here's the video though of routine working enough to play.
This works in dance mode as well.

https://youtu.be/P9AeevTYUsQ

**Comment by StefanoFiumara** [comment] 2016-09-03 23:19
I'm interested in this since I've played a few "couples" charts (i.e. doubles chart with rolls/holds) at the arcade with friends and found it insanely fun.

What is the difference between routine and couples mode?

I would love to have this on the style selection screen, alongside maybe a proper song list display in marathon mode :smile:

**Comment by dguzek** [comment] 2016-09-03 23:25
> I would love to have this on the style selection screen, alongside maybe a proper song list display in marathon mode 

I don't really have the time or the willpower currently to work on new features for Simply Love in any sort of timely fashion.  I will, of course, consider any pull requests that are submitted if you'd like to write the code, do the testing, and fix the bugs yourself. 😃

**Comment by StefanoFiumara** [comment] 2016-09-04 02:55
I've been picking up bits and pieces of lua as I make changes to the version of your theme that I'm running, but I'm having a hard time actually writing anything from scratch, maybe one day I'll dive deeper into it.

At the moment, though, I'm running a much older version of SL on Stepmania 5.0.9, I'll have to get around to upgrading if I want to seriously start learning this stuff so I can contribute, I do want to dive deeper into the whole lua thing. Lua is hard for me to grasp coming from a language like C#, though >_<
