### ISSUE TITLE
Dot placed incorrectly on ScreenEvaluation ScatterPlot

### ISSUE THREAD

**Issue by FishamanP** [dguzek/Simply-Love-SM5#77] opened 2017-11-25 01:17 UTC
Likely a simple off-by-1.

https://imgur.com/a/ahgV6

**Comment by dguzek** [comment] 2017-11-25 02:59
I've observed this bug before with very short songs.  It seems that my means of scaling the x-offset of judgment dots/lines is flawed.  It's [this line](https://github.com/dguzek/Simply-Love-SM5/blob/master/BGAnimations/ScreenEvaluation%20common/PerPlayer/ScatterPlot.lua#L47), in particular.

The problem is that the difference of `CurrentSecond-FirstSecond` can be greater than `TotalSeconds` (which shouldn't be possible), causing the `scale()` function to output a value that extends beyond the 300px of width available.  This only seems to happen with very short songs.

I am open to whatever fixes you can come up with.

**Comment by dguzek** [comment] 2018-02-04 22:40
This issue may have been resolved by pull request #94.  @FishamanP, you can pull the latest changes and test this?

Many thanks continue to go to @andrewipark for submitting good pull requests.

**Comment by FishamanP** [comment] 2018-02-05 00:41
I actually won't have access to suitable testing hardware for a few months, but I trust the testing done by Andrew. I'll comment here if I can eventually reproduce this with the updated theme.

**Closed** 2018-02-24 20:07 UTC
Labels: bug
